url=jdbc:postgresql://localhost:5432/postgres
username=postgres
password=zpletk
driver=org.postgresql.Driver
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
outputChangeLogFile=src/main/resources/db/changelog/db.changelog-master.yamldb/changelog/db.changelog-master.yaml